// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// qr_tau_para_diff_cpp
List qr_tau_para_diff_cpp(const arma::mat x, const arma::colvec y, const arma::rowvec weights, const arma::colvec taurange, const double tau_min, const double tol, const uint maxit, const uint max_num_tau, const bool use_residual);
RcppExport SEXP _qr_simplex_qr_tau_para_diff_cpp(SEXP xSEXP, SEXP ySEXP, SEXP weightsSEXP, SEXP taurangeSEXP, SEXP tau_minSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP max_num_tauSEXP, SEXP use_residualSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::colvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const arma::colvec >::type taurange(taurangeSEXP);
    Rcpp::traits::input_parameter< const double >::type tau_min(tau_minSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const uint >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const uint >::type max_num_tau(max_num_tauSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_residual(use_residualSEXP);
    rcpp_result_gen = Rcpp::wrap(qr_tau_para_diff_cpp(x, y, weights, taurange, tau_min, tol, maxit, max_num_tau, use_residual));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_qr_simplex_qr_tau_para_diff_cpp", (DL_FUNC) &_qr_simplex_qr_tau_para_diff_cpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_qr_simplex(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
