# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qr_tau_para_diff_cpp <- function(x, y, weights, taurange, tau_min = 1e-10, tol = 1e-14, maxit = 100000L, max_num_tau = 1000L, use_residual = TRUE) {
    .Call(`_qr_simplex_qr_tau_para_diff_cpp`, x, y, weights, taurange, tau_min, tol, maxit, max_num_tau, use_residual)
}

